#!/usr/bin/env python3
"""Generate canonical spacing for every size; never redraw the source paths."""
from copy import deepcopy
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
NS = 'http://www.w3.org/2000/svg'
# 52 additional viewBox units total = approximately 2 pixels at 48px.
SIDE_OFFSET = 26
# Original painter order: orange (6), yellow (2), red (4).
# These are the constituent paths of the left-hand flame; all others are right.
LEFT_PATHS = {(0, 1), (0, 3), (0, 5), (1, 1), (2, 1), (2, 3)}


def main():
    original = ET.parse(ROOT / 'commonfire-logo-source.svg').getroot()
    groups = list(original)
    if ([len(group) for group in groups] != [6, 2, 4]
            or any(group.tag != f'{{{NS}}}g' for group in groups)
            or any(path.tag != f'{{{NS}}}path' or 'transform' in path.attrib
                   for group in groups for path in group)):
        raise ValueError('Master structure changed; review left/right path mapping before rebuilding.')
    master = deepcopy(original)
    for group_index, group in enumerate(master):
        for path_index, path in enumerate(group):
            shift = -SIDE_OFFSET if (group_index, path_index) in LEFT_PATHS else SIDE_OFFSET
            path.set('transform', f'translate({shift} 0)')
    master.insert(0, ET.Comment(
        ' Generated by build-logo-master.py. Original paths, fills, and painter order are unchanged. '
        'Each side is translated 26 units outward; no scaling, reshaping, or rotation. '
    ))
    ET.register_namespace('', NS)
    ET.ElementTree(master).write(ROOT / 'commonfire-logo.svg', encoding='unicode')


if __name__ == '__main__':
    main()
